import {Josefin_Sans} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ToastProvider from "@/components/ToastProvider";

const josefin = Josefin_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Wanderlast Travel Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${ josefin.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <Navbar/>
        {children}
        <ToastProvider/>
        <Footer/>
        </body>
    </html>
  );
}
